### ISSUE TITLE
authentication failed

### ISSUE THREAD

**Issue by whoami-ru** [its-a-feature/Apfell#15]
Hi. I install as it say in documentation. after i run ./status_check.sh 
![3](https://user-images.githubusercontent.com/60693100/73925058-a7597080-48f7-11ea-8d67-a28aea5a45f7.PNG)
then "./display_output.sh apfell_apfell" and there is an error "FATAL:  password authentication failed for user "apfell_user"".
I don't modify file "__init__.py".

**Comment by its-a-feature** [comment]
Did you run the `./setup_apfell.sh` script?

**Comment by whoami-ru** [comment]
Yes

**Comment by its-a-feature** [comment]
try doing a `sudo ./start_apfell.sh` again? That error usually happens when the information from the setup script didn't get stamped in properly. Running the `start_apfell.sh` script again will stop all of the containers and make sure the changes get pulled into the docker containers.

**Comment by whoami-ru** [comment]
i tried to manually stopped the container and it didn't help

apfell_apfell container logs

wait-for-postgres.sh: waiting 5 seconds for 127.0.0.1:5432
wait-for-postgres.sh: 127.0.0.1:5432 is available after 0 seconds
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3768, in _create_connection
    return self._connect(self.database, **self.connect_kwargs)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 4164, in _connect
    conn = psycopg2.connect(database=database, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "apfell_user"
FATAL:  password authentication failed for user "apfell_user"


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3828, in execute_sql
    cursor = self.get_cursor()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3774, in get_cursor
    return self.get_conn().cursor()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3763, in get_conn
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3738, in connect
    self._local.conn = self._create_connection()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3768, in _create_connection
    return self._connect(self.database, **self.connect_kwargs)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3656, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3768, in _create_connection
    return self._connect(self.database, **self.connect_kwargs)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 4164, in _connect
    conn = psycopg2.connect(database=database, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
peewee.OperationalError: FATAL:  password authentication failed for user "apfell_user"
FATAL:  password authentication failed for user "apfell_user"


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Apfell/server.py", line 1, in <module>
    from app import apfell, dbloop, apfell_db, db_objects, use_ssl, listen_port, listen_ip, ssl_cert_path, ssl_key_path
  File "/Apfell/app/__init__.py", line 54, in <module>
    import app.routes
  File "/Apfell/app/routes/__init__.py", line 1, in <module>
    from app.routes import routes, operations_routes, websocket_routes, api_routes, payloads_routes, services_routes, authentication, reporting_routes
  File "/Apfell/app/routes/routes.py", line 6, in <module>
    from app.database_models.model import Operator, Operation, OperatorOperation, ATTACK, Artifact
  File "/Apfell/app/database_models/model.py", line 1499, in <module>
    Operator.create_table(True)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 5028, in create_table
    if fail_silently and cls.table_exists():
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 5024, in table_exists
    return cls._meta.db_table in cls._meta.database.get_tables(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 4199, in get_tables
    return [r for r, in self.execute_sql(query, (schema,)).fetchall()]
  File "/usr/local/lib/python3.6/site-packages/peewee_async.py", line 1042, in execute_sql
    return super().execute_sql(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3837, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3656, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3828, in execute_sql
    cursor = self.get_cursor()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3774, in get_cursor
    return self.get_conn().cursor()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3763, in get_conn
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3738, in connect
    self._local.conn = self._create_connection()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3768, in _create_connection
    return self._connect(self.database, **self.connect_kwargs)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3656, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 3768, in _create_connection
    return self._connect(self.database, **self.connect_kwargs)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 4164, in _connect
    conn = psycopg2.connect(database=database, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
peewee.OperationalError: FATAL:  password authentication failed for user "apfell_user"
FATAL:  password authentication failed for user "apfell_user"

**Comment by its-a-feature** [comment]
Yeah, so that's the error for when the apfell web server can't authenticate to the postgres database.  Can you look at the logs for the apfell_postgres container for any errors? If you look at `Apfell/postgres-docker/Dockerfile` you should see some lines that specify the `apfell_user` and the corresponding password. Make sure those are set to match what's in your `Apfell/apfell-docker/app/__init__.py` .

**Comment by whoami-ru** [comment]
You were right, there was an error in postgres-docker logs that the port is already in use. Because the postgres service was already running on my machine. Thank you!
