### ISSUE TITLE
macOS installation error

### ISSUE THREAD

**Issue by Soutcast** [its-a-feature/Apfell#4]
macOS: High Sierra
Python: 3.7.2

Trying to run `sudo python3 server.py` produces the following error:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3768, in _create_connection
    return self._connect(self.database, **self.connect_kwargs)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 4164, in _connect
    conn = psycopg2.connect(database=database, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  role "apfell_user" does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3828, in execute_sql
    cursor = self.get_cursor()
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3774, in get_cursor
    return self.get_conn().cursor()
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3763, in get_conn
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3738, in connect
    self._local.conn = self._create_connection()
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3768, in _create_connection
    return self._connect(self.database, **self.connect_kwargs)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3656, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3768, in _create_connection
    return self._connect(self.database, **self.connect_kwargs)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 4164, in _connect
    conn = psycopg2.connect(database=database, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
peewee.OperationalError: FATAL:  role "apfell_user" does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "server.py", line 1, in <module>
    from app import apfell, dbloop, apfell_db, db_objects, use_ssl, listen_port, listen_ip, ssl_cert_path, ssl_key_path
  File "/Users/username/Desktop/test/apfell/app/__init__.py", line 53, in <module>
    import app.routes
  File "/Users/username/Desktop/test/apfell/app/routes/__init__.py", line 1, in <module>
    from app.routes import routes, operations_routes, websocket_routes, api_routes, payloads_routes, services_routes, authentication, reporting_routes
  File "/Users/username/Desktop/test/apfell/app/routes/routes.py", line 6, in <module>
    from app.database_models.model import Operator, Operation, OperatorOperation, C2Profile, PayloadType, Command, CommandParameters, Transform, ATTACK, Artifact
  File "/Users/username/Desktop/test/apfell/app/database_models/model.py", line 1312, in <module>
    Operator.create_table(True)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 5028, in create_table
    if fail_silently and cls.table_exists():
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 5024, in table_exists
    return cls._meta.db_table in cls._meta.database.get_tables(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 4199, in get_tables
    return [r for r, in self.execute_sql(query, (schema,)).fetchall()]
  File "/usr/local/lib/python3.7/site-packages/peewee_async.py", line 1041, in execute_sql
    return super().execute_sql(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3837, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3656, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3828, in execute_sql
    cursor = self.get_cursor()
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3774, in get_cursor
    return self.get_conn().cursor()
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3763, in get_conn
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3738, in connect
    self._local.conn = self._create_connection()
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3768, in _create_connection
    return self._connect(self.database, **self.connect_kwargs)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3656, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 3768, in _create_connection
    return self._connect(self.database, **self.connect_kwargs)
  File "/usr/local/lib/python3.7/site-packages/peewee.py", line 4164, in _connect
    conn = psycopg2.connect(database=database, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
peewee.OperationalError: FATAL:  role "apfell_user" does not exist`

**Comment by Soutcast** [comment]
Seems to have resolved itself by running setup script multiple times

**Comment by its-a-feature** [comment]
Sorry for the late reply, that's interesting. It seemed like it didn't create the database user. I've noticed it being weird when running the server on macOS sometimes since there's a weird situation of homebrew not wanting you to run it as root, but still needing to run as root if you want to open the <1024 ports for web services. I'm glad you were able to get it fixed though! If you have any other issues let me know
