### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 0v3** [its-a-feature/Apfell#7]
Hello, 
I'm got an issue, after installing with your install script,
im on mac os High Sierra 10.13.6,

im getting this error after i run the "sudo python3 server.py"

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
[2019-04-10 08:57:01 +0200] [5970] [INFO] Goin' Fast @ http://0.0.0.0:80
Exception in callback <function callback at 0x10e6d4048>
handle: <Handle callback>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/peewee_async.py", line 1538, in _run_sql
    yield from cursor.execute(operation, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiopg/cursor.py", line 114, in execute
    yield from self._conn._poll(waiter, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiopg/connection.py", line 238, in _poll
    yield from asyncio.wait_for(self._waiter, timeout, loop=self._loop)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiopg/connection.py", line 135, in _ready
    state = self._conn.poll()
psycopg2.ProgrammingError: column t1.ui_config does not exist
LINE 1: ...gin", "t1"."active", "t1"."current_operation_id", "t1"."ui_c...
                                                             ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 49, in uvloop.loop.Handle._run
  File "server.py", line 22, in callback
    fetch_count = fut.result()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sanic/app.py", line 696, in create_server
    server_settings.get('loop')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sanic/app.py", line 709, in trigger_events
    await result
  File "/Users/bylogbot/tools/Apfell/app/routes/routes.py", line 278, in setup_initial_info
    await initial_setup()
  File "/Users/bylogbot/tools/Apfell/app/routes/routes.py", line 283, in initial_setup
    operators = await db_objects.execute(Operator.select())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/peewee_async.py", line 271, in execute
    return (yield from execute(query))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/peewee_async.py", line 435, in execute
    return (yield from coroutine(query))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/peewee_async.py", line 576, in select
    cursor = yield from _execute_query_async(query)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/peewee_async.py", line 1550, in _execute_query_async
    return (yield from _run_sql(query.database, *query.sql()))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/peewee_async.py", line 1543, in _run_sql
    return cursor
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/peewee.py", line 3656, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/peewee.py", line 135, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/peewee_async.py", line 1538, in _run_sql
    yield from cursor.execute(operation, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiopg/cursor.py", line 114, in execute
    yield from self._conn._poll(waiter, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiopg/connection.py", line 238, in _poll
    yield from asyncio.wait_for(self._waiter, timeout, loop=self._loop)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiopg/connection.py", line 135, in _ready
    state = self._conn.poll()
peewee.ProgrammingError: column t1.ui_config does not exist
LINE 1: ...gin", "t1"."active", "t1"."current_operation_id", "t1"."ui_c...
                                                             ^

**Comment by its-a-feature** [comment]
It looks like there's an issue with the database. Try running the `reset_db.sh` script and then running `python3 server.py` again. The `reset_db.sh` script just drops all of the tables for the `apfell_db` database in postgres so that the beginning of the `server.py` program can recreate it.

**Comment by its-a-feature** [comment]
Did that fix it? I'm also working on a docker solution that should help mitigate these kinds of issues

**Comment by 0v3** [comment]
It got resolved, I reinstalled postgres Server and It everything started working fine 👍
